services:
  flask-app:
    build:
      context: .
    ports:
      - "5003:5000"
    environment:
      # Defaults work for local DB. Override in .env when using external DB.
      DB_HOST: ${DB_HOST:-db}
      DB_USER: ${DB_USER:-appuser}
      DB_PASS: ${DB_PASS:-appsecret}
      DB_NAME: ${DB_NAME:-mydb}
      DB_PORT: ${DB_PORT:-3306}
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY:-change_me}
      FLASK_DEBUG: ${FLASK_DEBUG:-true}
      DB_SSL_MODE: ${DB_SSL_MODE:-disabled}
      DB_SSL_CA: ${DB_SSL_CA:-}
    # No depends_on needed; app waits for DB in code.

  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    # Only start this when we enable the "local-db" profile
    profiles: ["local-db"]
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appsecret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

volumes:
  db_data:
