version: "4.0"

services:
  flask-app:
    build:
      context: .
    ports:
      - "5003:5000"
    environment:
      - DB_HOST=${DB_HOST:-db} # Use external DB if DB_HOST is set, otherwise default to 'db'
      - DB_USER=${DB_USER:-root}
      - DB_PASS=${DB_PASS:-example}
      - DB_NAME=${DB_NAME:-mydb}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pexample"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s # Increased start period to allow MySQL more time to initialize

volumes:
  db_data:
